### ISSUE TITLE
 Cannot modify header information

### ISSUE THREAD

**Issue by luisrock** [avramovic/gumpress#1]
Hi. I am trying now and the licensing page is showing thew following warnings:

```
Warning: Cannot modify header information - headers already sent by (output started at /Users/maurolopes/phpSites/WP_students/students/wp-includes/formatting.php:5740) in /Users/maurolopes/phpSites/WP_students/students/wp-includes/pluggable.php on line 1340

Warning: Cannot modify header information - headers already sent by (output started at /Users/maurolopes/phpSites/WP_students/students/wp-includes/formatting.php:5740) in /Users/maurolopes/phpSites/WP_students/students/wp-includes/pluggable.php on line 1343
```

**Comment by avramovic** [comment]
Hi,

Whoa! I didn't expect anyone to be using this soon. :) While mostly done, GumPress is still WIP. Sorry about the problems you're having, but this error message does not reveal much. 

What WP version are you using? Do you have any other plugins enabled besides the plugin you're developing/integrating with GumPress? If so, can you disable all plugins besides the one you're working with and try again? Can you show the code used for integration (GumPress::register line)? Can you provide a screenshot of the error? I'd like to see exactly where it appears.

I have it installed locally on the latest WP right now (5.8.2) and can not reproduce it (with PHP's error_reporting set to E_ALL).

**Comment by luisrock** [comment]
I didn't know it was too soon. Anyway, I am postponing the licensing check on my new plugin. When I have costumers I'll worry about the licensing stuff... :) 

Sorry, but I've already removed GumPress from my code (so I can't help with the issue). But it looks very promising. I'll definitely check it out later. 

Thanks!
